version: 2
updates:
  - package-ecosystem: "bun"
    directory: "/react/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "[bun]"
      include: "scope"
    target-branch: "react-rewrite"
    groups:
      dev-deps:
        dependency-type: "development"
      prod-deps:
        dependency-type: "production"
