# Add 'workflows' label to any new or updated GitHub action workflow
workflows:
  - .github/workflows/*

components:
  - react/src/components/*

# Add the 'documentation' label to any changes in either of the documented files
documentation:
  - README.md
  - LICENSE
  - CODE_OF_CONDUCT.md
