[tools]
node = "24.19.0"
pnpm = "12.0.0-rc.10"


[settings]
experimental = true
pin = true


[tasks."web:dev"]
alias = ["web:up"]
description = "Start frontend development server. Save file(s) to see changes"
env._.path = "./node_modules/.bin"
dir = "{{ config_root }}"
run = "vite"

[tasks."web:install"]
description = "Pulls dependencies through pnpm"
env._.path = "./node_modules/.bin"
dir = "{{ config_root }}"
run = "pnpm install"

[tasks."web:build"]
description = "Builds the frontend for distribution/preview"
env._.path = "./node_modules/.bin"
dir = "{{ config_root }}"
run = "tsc -b && vite build"

[tasks."web:preview"]
description = "Previews frontend"
env._.path = "./node_modules/.bin"
dir = "{{ config_root }}"
run = "vite preview"

[tasks."web:clean-preview"]
description = "Cleans out dist and then previews frontend"
env._.path = "./node_modules/.bin"
dir = "{{ config_root }}"
run = ["rm -r dist", "tsc -b && vite build", "vite preview"]

[tasks."web:lint"]
description = "Lints the react codebase"
env._.path = "./node_modules/.bin"
dir = "{{ config_root }}"
run = ["oxlint --type-aware --type-check --deny-warnings src", "eslint src --cache --cache-location .eslintcache"]

[tasks."web:format"]
description = "Formats the react codebase"
env._.path = "./node_modules/.bin"
dir = "{{ config_root }}"
run = "oxfmt --write src"

[tasks."web:check"]
description = "Lints and formats the react codebase"
env._.path = "./node_modules/.bin"
dir = "{{ config_root }}"
run = [{"task" = "web:lint"}, { "task" = "web:format"}]

[tasks."web:generate:kanae"]
alias = ["web:generate:types"]
description = "Generates/regenerates the types from Kanae's openapi schema"
env._.path = "./node_modules/.bin"
dir = "{{ config_root }}"
usage = '''
arg "<file>" help="openapi schema to use"
'''
run = "openapi-ts --input ${usage_file}"
