// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl:
    | `${string}://kanae_openapi_b5fe247856d61d12db945073906652366ae409a1.json`
    | (string & {});
};

/**
 * ArchiveProject
 */
export type ArchiveProject = {
  /**
   * Active
   */
  active: boolean;
};

/**
 * AssignableRole
 */
export type AssignableRole = "admin" | "manager" | "leads";

/**
 * AttachedTagEntry
 */
export type AttachedTagEntry = {
  /**
   * Id
   */
  id: string;
  /**
   * Name
   */
  name: string;
  /**
   * Type
   */
  type: "Project" | "Event";
};

/**
 * AttachedTagResponse
 */
export type AttachedTagResponse = {
  /**
   * Detail
   */
  detail: string;
  /**
   * Entries
   */
  entries: Array<AttachedTagEntry>;
};

/**
 * AttendanceCodeResponse
 */
export type AttendanceCodeResponse = {
  /**
   * Code
   */
  code: string;
};

/**
 * AttendanceMember
 */
export type AttendanceMember = {
  /**
   * Id
   */
  id: string;
  /**
   * Name
   */
  name: string;
  /**
   * Planned
   */
  planned?: boolean | null;
  /**
   * Attended
   */
  attended: boolean;
};

/**
 * BadRequestResponse
 */
export type BadRequestResponse = {
  /**
   * Result
   */
  result?: string;
  /**
   * Detail
   */
  detail: string;
};

/**
 * BulkJoinMember
 */
export type BulkJoinMember = {
  /**
   * Id
   */
  id: string;
};

/**
 * ClientMember
 */
export type ClientMember = {
  /**
   * Id
   */
  id: string;
  /**
   * Name
   */
  name: string;
  /**
   * Email
   */
  email: string;
  /**
   * Display Name
   */
  display_name?: string | null;
  /**
   * Created At
   */
  created_at: string;
  /**
   * Projects
   */
  projects: Array<Projects>;
  /**
   * Events
   */
  events: Array<Events>;
  /**
   * Roles
   */
  roles: Array<Role>;
  session: ClientSession;
};

/**
 * ClientSession
 */
export type ClientSession = {
  /**
   * Aal
   */
  aal: "aal1" | "aal2";
  /**
   * Active
   */
  active: boolean;
  /**
   * Authenticated At
   */
  authenticated_at: string;
  /**
   * Issued At
   */
  issued_at: string;
  /**
   * Expires At
   */
  expires_at: string;
};

/**
 * CommitRequest
 */
export type CommitRequest = {
  /**
   * Hash
   */
  hash: string;
  /**
   * Content Type
   */
  content_type: string;
  /**
   * Size
   */
  size: number;
  /**
   * Upload Id
   */
  upload_id?: string | null;
  /**
   * Chunks
   */
  chunks?: Array<CompletedChunk> | null;
};

/**
 * CompletedChunk
 */
export type CompletedChunk = {
  /**
   * Number
   */
  number: number;
  /**
   * Etag
   */
  etag: string;
};

/**
 * ConflictResponse
 */
export type ConflictResponse = {
  /**
   * Result
   */
  result?: string;
  /**
   * Detail
   */
  detail: string;
};

/**
 * CreateInvite
 */
export type CreateInvite = {
  /**
   * Member Id
   */
  member_id: string;
  /**
   * Message
   */
  message?: string | null;
};

/**
 * CreateProject
 */
export type CreateProject = {
  /**
   * Name
   */
  name: string;
  /**
   * Description
   */
  description: string;
  /**
   * Link
   */
  link: string;
  /**
   * Type
   */
  type: "independent" | "sig_ai" | "sig_swe" | "sig_cyber" | "sig_data" | "sig_arch" | "sig_graph";
  /**
   * Tags
   */
  tags?: Array<string> | null;
  /**
   * Active
   */
  active: boolean;
  /**
   * Founded At
   */
  founded_at: string;
};

/**
 * CreateRequest
 */
export type CreateRequest = {
  /**
   * Message
   */
  message?: string | null;
};

/**
 * DeleteResponse
 */
export type DeleteResponse = {
  /**
   * Message
   */
  message?: string;
};

/**
 * EventTagsResponse
 */
export type EventTagsResponse = {
  /**
   * Tags
   */
  tags: Array<string>;
};

/**
 * EventThumbnail
 */
export type EventThumbnail = {
  /**
   * Hash
   */
  hash: string;
  /**
   * Url
   */
  url: string;
};

/**
 * Events
 */
export type Events = {
  /**
   * Id
   */
  id: string;
  /**
   * Name
   */
  name: string;
  /**
   * Description
   */
  description: string;
  /**
   * Start At
   */
  start_at: string;
  /**
   * End At
   */
  end_at: string;
  /**
   * Location
   */
  location: string;
  /**
   * Type
   */
  type:
    | "general"
    | "sig_ai"
    | "sig_swe"
    | "sig_cyber"
    | "sig_data"
    | "sig_arch"
    | "sig_graph"
    | "social"
    | "misc";
  /**
   * Timezone
   */
  timezone: string;
  /**
   * Creator Id
   */
  creator_id?: string | null;
};

/**
 * ForbiddenResponse
 */
export type ForbiddenResponse = {
  /**
   * Result
   */
  result?: string;
  /**
   * Detail
   */
  detail: string;
};

/**
 * FullEvents
 */
export type FullEvents = {
  /**
   * Id
   */
  id: string;
  /**
   * Name
   */
  name: string;
  /**
   * Description
   */
  description: string;
  /**
   * Start At
   */
  start_at: string;
  /**
   * End At
   */
  end_at: string;
  /**
   * Location
   */
  location: string;
  /**
   * Type
   */
  type:
    | "general"
    | "sig_ai"
    | "sig_swe"
    | "sig_cyber"
    | "sig_data"
    | "sig_arch"
    | "sig_graph"
    | "social"
    | "misc";
  /**
   * Timezone
   */
  timezone: string;
  thumbnail?: EventThumbnail | null;
  /**
   * Tags
   */
  tags?: Array<string> | null;
  /**
   * Creator Id
   */
  creator_id?: string | null;
};

/**
 * FullProjects
 */
export type FullProjects = {
  /**
   * Id
   */
  id: string;
  /**
   * Name
   */
  name: string;
  /**
   * Description
   */
  description: string;
  /**
   * Link
   */
  link: string;
  thumbnail?: ProjectThumbnail | null;
  /**
   * Members
   */
  members: Array<ProjectMember>;
  /**
   * Type
   */
  type: "independent" | "sig_ai" | "sig_swe" | "sig_cyber" | "sig_data" | "sig_arch" | "sig_graph";
  /**
   * Tags
   */
  tags?: Array<string> | null;
  /**
   * Active
   */
  active: boolean;
  /**
   * Join Policy
   */
  join_policy: "open" | "request" | "closed";
  /**
   * Founded At
   */
  founded_at: string;
};

/**
 * FullTags
 */
export type FullTags = {
  /**
   * Id
   */
  id: number;
  /**
   * Title
   */
  title: string;
  /**
   * Description
   */
  description: string;
  /**
   * In Use
   */
  in_use: boolean;
};

/**
 * HTTPExceptionResponse
 */
export type HttpExceptionResponse = {
  /**
   * Result
   */
  result?: string;
  /**
   * Detail
   */
  detail: string;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
  /**
   * Detail
   */
  detail?: Array<ValidationError>;
};

/**
 * InviteActionResponse
 */
export type InviteActionResponse = {
  /**
   * Id
   */
  id: string;
  /**
   * Status
   */
  status: "accepted" | "declined" | "revoked";
};

/**
 * JoinResponse
 */
export type JoinResponse = {
  /**
   * Message
   */
  message?: string;
};

/**
 * KanaePages[AttendanceMember]
 */
export type KanaePagesAttendanceMember = {
  /**
   * Data
   */
  data: Array<AttendanceMember>;
  /**
   * Total
   */
  total: number;
};

/**
 * KanaePages[FullEvents]
 */
export type KanaePagesFullEvents = {
  /**
   * Data
   */
  data: Array<FullEvents>;
  /**
   * Total
   */
  total: number;
};

/**
 * KanaePages[FullProjects]
 */
export type KanaePagesFullProjects = {
  /**
   * Data
   */
  data: Array<FullProjects>;
  /**
   * Total
   */
  total: number;
};

/**
 * KanaePages[SimpleMember]
 */
export type KanaePagesSimpleMember = {
  /**
   * Data
   */
  data: Array<SimpleMember>;
  /**
   * Total
   */
  total: number;
};

/**
 * MediaRecord
 */
export type MediaRecord = {
  /**
   * Hash
   */
  hash: string;
  /**
   * Content Type
   */
  content_type: string;
  /**
   * Kind
   */
  kind: "image" | "video";
  /**
   * Size
   */
  size: number;
  /**
   * Created At
   */
  created_at: string;
  /**
   * Url
   */
  url: string;
};

/**
 * Member
 */
export type Member = {
  /**
   * Id
   */
  id: string;
  /**
   * Name
   */
  name: string;
  /**
   * Created At
   */
  created_at: string;
  /**
   * Projects
   */
  projects: Array<Projects>;
  /**
   * Events
   */
  events: Array<Events>;
};

/**
 * MemberRoles
 */
export type MemberRoles = {
  /**
   * Roles
   */
  roles: Array<Role>;
};

/**
 * ModifiedEvent
 */
export type ModifiedEvent = {
  /**
   * Name
   */
  name: string;
  /**
   * Description
   */
  description: string;
  /**
   * Location
   */
  location: string;
};

/**
 * ModifiedEventWithDatetime
 */
export type ModifiedEventWithDatetime = {
  /**
   * Name
   */
  name: string;
  /**
   * Description
   */
  description: string;
  /**
   * Location
   */
  location: string;
  /**
   * Start At
   */
  start_at: string;
  /**
   * End At
   */
  end_at: string;
  /**
   * Timezone
   */
  timezone: string;
};

/**
 * ModifiedProject
 */
export type ModifiedProject = {
  /**
   * Name
   */
  name: string;
  /**
   * Description
   */
  description: string;
  /**
   * Link
   */
  link: string;
};

/**
 * ModifiedTag
 */
export type ModifiedTag = {
  /**
   * Title
   */
  title: string;
  /**
   * Description
   */
  description: string;
};

/**
 * ModifyEventTags
 */
export type ModifyEventTags = {
  /**
   * Tags
   */
  tags: Array<string>;
};

/**
 * ModifyJoinPolicy
 */
export type ModifyJoinPolicy = {
  /**
   * Join Policy
   */
  join_policy: "open" | "request" | "closed";
};

/**
 * ModifyProjectTags
 */
export type ModifyProjectTags = {
  /**
   * Tags
   */
  tags: Array<string>;
};

/**
 * ModifyRoleAction
 */
export type ModifyRoleAction = "grant" | "revoke";

/**
 * ModifyRoleRequest
 */
export type ModifyRoleRequest = {
  role: AssignableRole;
  action: ModifyRoleAction;
};

/**
 * MultipartUploadResponse
 */
export type MultipartUploadResponse = {
  /**
   * Upload Id
   */
  upload_id: string;
  /**
   * Size
   */
  size: number;
  /**
   * Chunks
   */
  chunks: Array<UploadChunk>;
};

/**
 * NotFoundResponse
 */
export type NotFoundResponse = {
  /**
   * Result
   */
  result?: string;
  /**
   * Detail
   */
  detail?: string;
};

/**
 * ProjectInvite
 */
export type ProjectInvite = {
  /**
   * Id
   */
  id: string;
  /**
   * Project Id
   */
  project_id: string;
  member: ProjectMember;
  /**
   * Invited By
   */
  invited_by?: string | null;
  /**
   * Kind
   */
  kind: "invite" | "request";
  /**
   * Status
   */
  status: "pending" | "accepted" | "declined" | "revoked" | "expired";
  /**
   * Message
   */
  message?: string | null;
  /**
   * Responded At
   */
  responded_at?: string | null;
  /**
   * Expires At
   */
  expires_at?: string | null;
  /**
   * Created At
   */
  created_at: string;
};

/**
 * ProjectMember
 */
export type ProjectMember = {
  /**
   * Id
   */
  id: string;
  /**
   * Name
   */
  name: string;
};

/**
 * ProjectTagsResponse
 */
export type ProjectTagsResponse = {
  /**
   * Tags
   */
  tags: Array<string>;
};

/**
 * ProjectThumbnail
 */
export type ProjectThumbnail = {
  /**
   * Hash
   */
  hash: string;
  /**
   * Url
   */
  url: string;
};

/**
 * Projects
 */
export type Projects = {
  /**
   * Id
   */
  id: string;
  /**
   * Name
   */
  name: string;
  /**
   * Description
   */
  description: string;
  /**
   * Link
   */
  link: string;
  /**
   * Type
   */
  type: "independent" | "sig_ai" | "sig_swe" | "sig_cyber" | "sig_data" | "sig_arch" | "sig_graph";
  /**
   * Tags
   */
  tags?: Array<string> | null;
  /**
   * Active
   */
  active: boolean;
  /**
   * Join Policy
   */
  join_policy: "open" | "request" | "closed";
  /**
   * Founded At
   */
  founded_at: string;
};

/**
 * ReorderRequest
 */
export type ReorderRequest = {
  /**
   * Hashes
   */
  hashes: Array<string>;
};

/**
 * Role
 */
export type Role = "root" | "admin" | "manager" | "leads";

/**
 * SetThumbnailRequest
 */
export type SetThumbnailRequest = {
  /**
   * Hash
   */
  hash: string;
  /**
   * Content Type
   */
  content_type: string;
};

/**
 * SimpleMember
 */
export type SimpleMember = {
  /**
   * Id
   */
  id: string;
  /**
   * Name
   */
  name: string;
  /**
   * Display Name
   */
  display_name?: string | null;
  /**
   * Email
   */
  email: string;
  /**
   * Created At
   */
  created_at: string;
};

/**
 * SimpleUploadResponse
 */
export type SimpleUploadResponse = {
  /**
   * Url
   */
  url: string;
};

/**
 * SuccessResponse
 */
export type SuccessResponse = {
  /**
   * Message
   */
  message: string;
};

/**
 * Tags
 */
export type Tags = {
  /**
   * Id
   */
  id: number;
  /**
   * Title
   */
  title: string;
  /**
   * Description
   */
  description: string;
};

/**
 * UploadChunk
 */
export type UploadChunk = {
  /**
   * Index
   */
  index: number;
  /**
   * Url
   */
  url: string;
  /**
   * Size
   */
  size: number;
};

/**
 * UploadRequest
 */
export type UploadRequest = {
  /**
   * Hash
   */
  hash: string;
  /**
   * Content Type
   */
  content_type: string;
  /**
   * Size
   */
  size: number;
};

/**
 * ValidationError
 */
export type ValidationError = {
  /**
   * Location
   */
  loc: Array<string | number>;
  /**
   * Message
   */
  msg: string;
  /**
   * Error Type
   */
  type: string;
  /**
   * Input
   */
  input?: unknown;
  /**
   * Context
   */
  ctx?: {
    [key: string]: unknown;
  };
};

/**
 * VerifyFailedResponse
 */
export type VerifyFailedResponse = {
  /**
   * Result
   */
  result?: string;
  /**
   * Detail
   */
  detail: string;
  /**
   * Message
   */
  message?: string;
};

/**
 * VerifyRequest
 */
export type VerifyRequest = {
  /**
   * Code
   */
  code: string;
};

export type ListEventsData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Name
     */
    name?: string | null;
    /**
     * Before
     */
    before?: string | null;
    /**
     * After
     */
    after?: string | null;
    /**
     * Page
     */
    page?: number;
    /**
     * Size
     */
    size?: number;
  };
  url: "/events";
};

export type ListEventsResponses = {
  /**
   * Successful Response
   */
  200: KanaePagesFullEvents;
};

export type ListEventsResponse = ListEventsResponses[keyof ListEventsResponses];

export type DeleteEventData = {
  body?: never;
  path: {
    /**
     * Event Id
     */
    event_id: string;
  };
  query?: never;
  url: "/events/{event_id}";
};

export type DeleteEventErrors = {
  /**
   * Not Found
   */
  404: NotFoundResponse;
};

export type DeleteEventError = DeleteEventErrors[keyof DeleteEventErrors];

export type DeleteEventResponses = {
  /**
   * Successful Response
   */
  200: DeleteResponse;
};

export type DeleteEventResponse = DeleteEventResponses[keyof DeleteEventResponses];

export type GetEventData = {
  body?: never;
  path: {
    /**
     * Event Id
     */
    event_id: string;
  };
  query?: never;
  url: "/events/{event_id}";
};

export type GetEventErrors = {
  /**
   * Not Found
   */
  404: NotFoundResponse;
};

export type GetEventError = GetEventErrors[keyof GetEventErrors];

export type GetEventResponses = {
  /**
   * Successful Response
   */
  200: FullEvents;
};

export type GetEventResponse = GetEventResponses[keyof GetEventResponses];

export type EditEventData = {
  /**
   * Req
   */
  body: ModifiedEvent | ModifiedEventWithDatetime;
  path: {
    /**
     * Event Id
     */
    event_id: string;
  };
  query?: never;
  url: "/events/{event_id}";
};

export type EditEventErrors = {
  /**
   * Not Found
   */
  404: NotFoundResponse;
};

export type EditEventError = EditEventErrors[keyof EditEventErrors];

export type EditEventResponses = {
  /**
   * Successful Response
   */
  200: Events;
};

export type EditEventResponse = EditEventResponses[keyof EditEventResponses];

export type CreateEventsData = {
  body: Events;
  path?: never;
  query?: never;
  url: "/events/create";
};

export type CreateEventsResponses = {
  /**
   * Successful Response
   */
  200: Events;
};

export type CreateEventsResponse = CreateEventsResponses[keyof CreateEventsResponses];

export type UploadEventThumbnailData = {
  body: UploadRequest;
  path: {
    /**
     * Event Id
     */
    event_id: string;
  };
  query?: never;
  url: "/events/{event_id}/thumbnail/upload";
};

export type UploadEventThumbnailErrors = {
  /**
   * Bad Request
   */
  400: BadRequestResponse;
  /**
   * Forbidden
   */
  403: ForbiddenResponse;
  /**
   * Content Too Large
   */
  413: HttpExceptionResponse;
};

export type UploadEventThumbnailError =
  UploadEventThumbnailErrors[keyof UploadEventThumbnailErrors];

export type UploadEventThumbnailResponses = {
  /**
   * Response Uploadeventthumbnail
   *
   * Successful Response
   */
  200: MediaRecord;
};

export type UploadEventThumbnailResponse =
  UploadEventThumbnailResponses[keyof UploadEventThumbnailResponses];

export type CommitEventThumbnailData = {
  body: UploadRequest;
  path: {
    /**
     * Event Id
     */
    event_id: string;
  };
  query?: never;
  url: "/events/{event_id}/thumbnail/commit";
};

export type CommitEventThumbnailErrors = {
  /**
   * Bad Request
   */
  400: BadRequestResponse;
  /**
   * Forbidden
   */
  403: ForbiddenResponse;
  /**
   * Not Found
   */
  404: NotFoundResponse;
  /**
   * Conflict
   */
  409: ConflictResponse;
  /**
   * Content Too Large
   */
  413: HttpExceptionResponse;
};

export type CommitEventThumbnailError =
  CommitEventThumbnailErrors[keyof CommitEventThumbnailErrors];

export type CommitEventThumbnailResponses = {
  /**
   * Successful Response
   */
  200: EventThumbnail;
};

export type CommitEventThumbnailResponse =
  CommitEventThumbnailResponses[keyof CommitEventThumbnailResponses];

export type RemoveEventThumbnailData = {
  body?: never;
  path: {
    /**
     * Event Id
     */
    event_id: string;
  };
  query?: never;
  url: "/events/{event_id}/thumbnail";
};

export type RemoveEventThumbnailErrors = {
  /**
   * Forbidden
   */
  403: ForbiddenResponse;
  /**
   * Not Found
   */
  404: NotFoundResponse;
};

export type RemoveEventThumbnailError =
  RemoveEventThumbnailErrors[keyof RemoveEventThumbnailErrors];

export type RemoveEventThumbnailResponses = {
  /**
   * Successful Response
   */
  200: DeleteResponse;
};

export type RemoveEventThumbnailResponse =
  RemoveEventThumbnailResponses[keyof RemoveEventThumbnailResponses];

export type SetEventThumbnailData = {
  body: SetThumbnailRequest;
  path: {
    /**
     * Event Id
     */
    event_id: string;
  };
  query?: never;
  url: "/events/{event_id}/thumbnail";
};

export type SetEventThumbnailErrors = {
  /**
   * Bad Request
   */
  400: BadRequestResponse;
  /**
   * Forbidden
   */
  403: ForbiddenResponse;
  /**
   * Not Found
   */
  404: NotFoundResponse;
};

export type SetEventThumbnailError = SetEventThumbnailErrors[keyof SetEventThumbnailErrors];

export type SetEventThumbnailResponses = {
  /**
   * Successful Response
   */
  200: SuccessResponse;
};

export type SetEventThumbnailResponse =
  SetEventThumbnailResponses[keyof SetEventThumbnailResponses];

export type ClearEventTagsData = {
  body?: never;
  path: {
    /**
     * Event Id
     */
    event_id: string;
  };
  query?: never;
  url: "/events/{event_id}/tags";
};

export type ClearEventTagsErrors = {
  /**
   * Not Found
   */
  404: NotFoundResponse;
};

export type ClearEventTagsError = ClearEventTagsErrors[keyof ClearEventTagsErrors];

export type ClearEventTagsResponses = {
  /**
   * Successful Response
   */
  200: DeleteResponse;
};

export type ClearEventTagsResponse = ClearEventTagsResponses[keyof ClearEventTagsResponses];

export type EditEventTagsData = {
  body: ModifyEventTags;
  path: {
    /**
     * Event Id
     */
    event_id: string;
  };
  query?: never;
  url: "/events/{event_id}/tags";
};

export type EditEventTagsErrors = {
  /**
   * Not Found
   */
  404: NotFoundResponse;
};

export type EditEventTagsError = EditEventTagsErrors[keyof EditEventTagsErrors];

export type EditEventTagsResponses = {
  /**
   * Successful Response
   */
  200: EventTagsResponse;
};

export type EditEventTagsResponse = EditEventTagsResponses[keyof EditEventTagsResponses];

export type JoinEventData = {
  body?: never;
  path: {
    /**
     * Event Id
     */
    event_id: string;
  };
  query?: never;
  url: "/events/{event_id}/join";
};

export type JoinEventErrors = {
  /**
   * Forbidden
   */
  403: ForbiddenResponse;
  /**
   * Not Found
   */
  404: NotFoundResponse;
  /**
   * Conflict
   */
  409: ConflictResponse;
};

export type JoinEventError = JoinEventErrors[keyof JoinEventErrors];

export type JoinEventResponses = {
  /**
   * Successful Response
   */
  200: JoinResponse;
};

export type JoinEventResponse = JoinEventResponses[keyof JoinEventResponses];

export type VerifyAttendanceData = {
  body: VerifyRequest;
  path: {
    /**
     * Event Id
     */
    event_id: string;
  };
  query?: never;
  url: "/events/{event_id}/verify";
};

export type VerifyAttendanceErrors = {
  /**
   * Forbidden
   */
  403: VerifyFailedResponse;
  /**
   * Not Found
   */
  404: NotFoundResponse;
  /**
   * Conflict
   */
  409: ConflictResponse;
};

export type VerifyAttendanceError = VerifyAttendanceErrors[keyof VerifyAttendanceErrors];

export type VerifyAttendanceResponses = {
  /**
   * Successful Response
   */
  200: SuccessResponse;
};

export type VerifyAttendanceResponse = VerifyAttendanceResponses[keyof VerifyAttendanceResponses];

export type ListEventAttendanceData = {
  body?: never;
  path: {
    /**
     * Event Id
     */
    event_id: string;
  };
  query?: {
    /**
     * Page
     */
    page?: number;
    /**
     * Size
     */
    size?: number;
  };
  url: "/events/{event_id}/attendance";
};

export type ListEventAttendanceErrors = {
  /**
   * Forbidden
   */
  403: ForbiddenResponse;
};

export type ListEventAttendanceError = ListEventAttendanceErrors[keyof ListEventAttendanceErrors];

export type ListEventAttendanceResponses = {
  /**
   * Successful Response
   */
  200: KanaePagesAttendanceMember;
};

export type ListEventAttendanceResponse =
  ListEventAttendanceResponses[keyof ListEventAttendanceResponses];

export type GetAttendanceCodeData = {
  body?: never;
  path: {
    /**
     * Event Id
     */
    event_id: string;
  };
  query?: never;
  url: "/events/{event_id}/attendance-code";
};

export type GetAttendanceCodeErrors = {
  /**
   * Not Found
   */
  404: NotFoundResponse;
};

export type GetAttendanceCodeError = GetAttendanceCodeErrors[keyof GetAttendanceCodeErrors];

export type GetAttendanceCodeResponses = {
  /**
   * Successful Response
   */
  200: AttendanceCodeResponse;
};

export type GetAttendanceCodeResponse =
  GetAttendanceCodeResponses[keyof GetAttendanceCodeResponses];

export type RemoveAttendanceData = {
  body?: never;
  path: {
    /**
     * Event Id
     */
    event_id: string;
    /**
     * Member Id
     */
    member_id: string;
  };
  query?: never;
  url: "/events/{event_id}/attendance/{member_id}";
};

export type RemoveAttendanceErrors = {
  /**
   * Not Found
   */
  404: NotFoundResponse;
};

export type RemoveAttendanceError = RemoveAttendanceErrors[keyof RemoveAttendanceErrors];

export type RemoveAttendanceResponses = {
  /**
   * Successful Response
   */
  200: DeleteResponse;
};

export type RemoveAttendanceResponse = RemoveAttendanceResponses[keyof RemoveAttendanceResponses];

export type ListMembersData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Query
     */
    query?: string | null;
    /**
     * Page
     */
    page?: number;
    /**
     * Size
     */
    size?: number;
  };
  url: "/members";
};

export type ListMembersResponses = {
  /**
   * Successful Response
   */
  200: KanaePagesSimpleMember;
};

export type ListMembersResponse = ListMembersResponses[keyof ListMembersResponses];

export type DeleteLoggedAccountData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/members/me";
};

export type DeleteLoggedAccountErrors = {
  /**
   * Not Found
   */
  404: NotFoundResponse;
};

export type DeleteLoggedAccountError = DeleteLoggedAccountErrors[keyof DeleteLoggedAccountErrors];

export type DeleteLoggedAccountResponses = {
  /**
   * Successful Response
   */
  200: DeleteResponse;
};

export type DeleteLoggedAccountResponse =
  DeleteLoggedAccountResponses[keyof DeleteLoggedAccountResponses];

export type GetLoggedMemberData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/members/me";
};

export type GetLoggedMemberErrors = {
  /**
   * Not Found
   */
  404: NotFoundResponse;
};

export type GetLoggedMemberError = GetLoggedMemberErrors[keyof GetLoggedMemberErrors];

export type GetLoggedMemberResponses = {
  /**
   * Successful Response
   */
  200: ClientMember;
};

export type GetLoggedMemberResponse = GetLoggedMemberResponses[keyof GetLoggedMemberResponses];

export type DeleteMemberData = {
  body?: never;
  path: {
    /**
     * Member Id
     */
    member_id: string;
  };
  query?: never;
  url: "/members/{member_id}";
};

export type DeleteMemberErrors = {
  /**
   * Not Found
   */
  404: NotFoundResponse;
  /**
   * Conflict
   */
  409: ConflictResponse;
};

export type DeleteMemberError = DeleteMemberErrors[keyof DeleteMemberErrors];

export type DeleteMemberResponses = {
  /**
   * Successful Response
   */
  200: DeleteResponse;
};

export type DeleteMemberResponse = DeleteMemberResponses[keyof DeleteMemberResponses];

export type GetMemberData = {
  body?: never;
  path: {
    /**
     * Member Id
     */
    member_id: string;
  };
  query?: never;
  url: "/members/{member_id}";
};

export type GetMemberErrors = {
  /**
   * Not Found
   */
  404: NotFoundResponse;
};

export type GetMemberError = GetMemberErrors[keyof GetMemberErrors];

export type GetMemberResponses = {
  /**
   * Successful Response
   */
  200: Member;
};

export type GetMemberResponse = GetMemberResponses[keyof GetMemberResponses];

export type GetLoggedProjectsData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Since
     */
    since?: string | null;
  };
  url: "/members/me/projects";
};

export type GetLoggedProjectsResponses = {
  /**
   * Response Getloggedprojects
   *
   * Successful Response
   */
  200: Projects;
};

export type GetLoggedProjectsResponse =
  GetLoggedProjectsResponses[keyof GetLoggedProjectsResponses];

export type ListMyProjectInvitesData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Status
     */
    status?: "pending" | "accepted" | "declined" | "revoked" | "expired" | null;
    /**
     * Kind
     */
    kind?: "invite" | "request" | null;
  };
  url: "/members/me/projects/invites";
};

export type ListMyProjectInvitesResponses = {
  /**
   * Response 200 Listmyprojectinvites
   *
   * Successful Response
   */
  200: Array<ProjectInvite>;
};

export type ListMyProjectInvitesResponse =
  ListMyProjectInvitesResponses[keyof ListMyProjectInvitesResponses];

export type GetLoggedEventsData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Planned
     */
    planned?: boolean | null;
    /**
     * Attended
     */
    attended?: boolean | null;
    /**
     * Upcoming
     */
    upcoming?: boolean | null;
    /**
     * Past
     */
    past?: boolean | null;
  };
  url: "/members/me/events";
};

export type GetLoggedEventsResponses = {
  /**
   * Response Getloggedevents
   *
   * Successful Response
   */
  200: Array<FullEvents>;
};

export type GetLoggedEventsResponse = GetLoggedEventsResponses[keyof GetLoggedEventsResponses];

export type LogoutMemberData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/members/logout";
};

export type LogoutMemberResponses = {
  /**
   * Successful Response
   */
  200: SuccessResponse;
};

export type LogoutMemberResponse = LogoutMemberResponses[keyof LogoutMemberResponses];

export type GetMemberRolesData = {
  body?: never;
  path: {
    /**
     * Member Id
     */
    member_id: string;
  };
  query?: never;
  url: "/members/{member_id}/roles";
};

export type GetMemberRolesErrors = {
  /**
   * Not Found
   */
  404: NotFoundResponse;
};

export type GetMemberRolesError = GetMemberRolesErrors[keyof GetMemberRolesErrors];

export type GetMemberRolesResponses = {
  /**
   * Successful Response
   */
  200: MemberRoles;
};

export type GetMemberRolesResponse = GetMemberRolesResponses[keyof GetMemberRolesResponses];

export type ModifyMemberRoleData = {
  body: ModifyRoleRequest;
  path: {
    /**
     * Member Id
     */
    member_id: string;
  };
  query?: never;
  url: "/members/{member_id}/role";
};

export type ModifyMemberRoleErrors = {
  /**
   * Not Found
   */
  404: NotFoundResponse;
  /**
   * Conflict
   */
  409: ConflictResponse;
};

export type ModifyMemberRoleError = ModifyMemberRoleErrors[keyof ModifyMemberRoleErrors];

export type ModifyMemberRoleResponses = {
  /**
   * Successful Response
   */
  200: SuccessResponse;
};

export type ModifyMemberRoleResponse = ModifyMemberRoleResponses[keyof ModifyMemberRoleResponses];

export type ListProjectsData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Name
     */
    name?: string | null;
    /**
     * Since
     */
    since?: string | null;
    /**
     * Until
     */
    until?: string | null;
    /**
     * Active
     */
    active?: boolean | null;
    /**
     * Page
     */
    page?: number;
    /**
     * Size
     */
    size?: number;
  };
  url: "/projects";
};

export type ListProjectsResponses = {
  /**
   * Successful Response
   */
  200: KanaePagesFullProjects;
};

export type ListProjectsResponse = ListProjectsResponses[keyof ListProjectsResponses];

export type ListAllProjectInvitesData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Status
     */
    status?: "pending" | "accepted" | "declined" | "revoked" | "expired" | null;
    /**
     * Kind
     */
    kind?: "invite" | "request" | null;
  };
  url: "/projects/invites";
};

export type ListAllProjectInvitesErrors = {
  /**
   * Forbidden
   */
  403: ForbiddenResponse;
};

export type ListAllProjectInvitesError =
  ListAllProjectInvitesErrors[keyof ListAllProjectInvitesErrors];

export type ListAllProjectInvitesResponses = {
  /**
   * Response 200 Listallprojectinvites
   *
   * Successful Response
   */
  200: Array<ProjectInvite>;
};

export type ListAllProjectInvitesResponse =
  ListAllProjectInvitesResponses[keyof ListAllProjectInvitesResponses];

export type DeleteProjectData = {
  body?: never;
  path: {
    /**
     * Project Id
     */
    project_id: string;
  };
  query?: never;
  url: "/projects/{project_id}";
};

export type DeleteProjectErrors = {
  /**
   * Not Found
   */
  404: NotFoundResponse;
};

export type DeleteProjectError = DeleteProjectErrors[keyof DeleteProjectErrors];

export type DeleteProjectResponses = {
  /**
   * Successful Response
   */
  200: DeleteResponse;
};

export type DeleteProjectResponse = DeleteProjectResponses[keyof DeleteProjectResponses];

export type GetProjectData = {
  body?: never;
  path: {
    /**
     * Project Id
     */
    project_id: string;
  };
  query?: never;
  url: "/projects/{project_id}";
};

export type GetProjectErrors = {
  /**
   * Not Found
   */
  404: NotFoundResponse;
};

export type GetProjectError = GetProjectErrors[keyof GetProjectErrors];

export type GetProjectResponses = {
  /**
   * Successful Response
   */
  200: FullProjects;
};

export type GetProjectResponse = GetProjectResponses[keyof GetProjectResponses];

export type EditProjectData = {
  body: ModifiedProject;
  path: {
    /**
     * Project Id
     */
    project_id: string;
  };
  query?: never;
  url: "/projects/{project_id}";
};

export type EditProjectErrors = {
  /**
   * Not Found
   */
  404: NotFoundResponse;
};

export type EditProjectError = EditProjectErrors[keyof EditProjectErrors];

export type EditProjectResponses = {
  /**
   * Successful Response
   */
  200: Projects;
};

export type EditProjectResponse = EditProjectResponses[keyof EditProjectResponses];

export type ArchiveProjectData = {
  body: ArchiveProject;
  path: {
    /**
     * Project Id
     */
    project_id: string;
  };
  query?: never;
  url: "/projects/{project_id}/archive";
};

export type ArchiveProjectErrors = {
  /**
   * Not Found
   */
  404: NotFoundResponse;
};

export type ArchiveProjectError = ArchiveProjectErrors[keyof ArchiveProjectErrors];

export type ArchiveProjectResponses = {
  /**
   * Successful Response
   */
  200: Projects;
};

export type ArchiveProjectResponse = ArchiveProjectResponses[keyof ArchiveProjectResponses];

export type ClearProjectTagsData = {
  body?: never;
  path: {
    /**
     * Project Id
     */
    project_id: string;
  };
  query?: never;
  url: "/projects/{project_id}/tags";
};

export type ClearProjectTagsErrors = {
  /**
   * Not Found
   */
  404: NotFoundResponse;
};

export type ClearProjectTagsError = ClearProjectTagsErrors[keyof ClearProjectTagsErrors];

export type ClearProjectTagsResponses = {
  /**
   * Successful Response
   */
  200: DeleteResponse;
};

export type ClearProjectTagsResponse = ClearProjectTagsResponses[keyof ClearProjectTagsResponses];

export type EditProjectTagsData = {
  body: ModifyProjectTags;
  path: {
    /**
     * Project Id
     */
    project_id: string;
  };
  query?: never;
  url: "/projects/{project_id}/tags";
};

export type EditProjectTagsErrors = {
  /**
   * Not Found
   */
  404: NotFoundResponse;
};

export type EditProjectTagsError = EditProjectTagsErrors[keyof EditProjectTagsErrors];

export type EditProjectTagsResponses = {
  /**
   * Successful Response
   */
  200: ProjectTagsResponse;
};

export type EditProjectTagsResponse = EditProjectTagsResponses[keyof EditProjectTagsResponses];

export type CreateProjectData = {
  body: CreateProject;
  path?: never;
  query?: never;
  url: "/projects/create";
};

export type CreateProjectErrors = {
  /**
   * Bad Gateway
   */
  502: HttpExceptionResponse;
};

export type CreateProjectError = CreateProjectErrors[keyof CreateProjectErrors];

export type CreateProjectResponses = {
  /**
   * Successful Response
   */
  200: Projects;
};

export type CreateProjectResponse = CreateProjectResponses[keyof CreateProjectResponses];

export type JoinProjectData = {
  body?: never;
  path: {
    /**
     * Project Id
     */
    project_id: string;
  };
  query?: never;
  url: "/projects/{project_id}/join";
};

export type JoinProjectErrors = {
  /**
   * Conflict
   */
  409: ConflictResponse;
};

export type JoinProjectError = JoinProjectErrors[keyof JoinProjectErrors];

export type JoinProjectResponses = {
  /**
   * Successful Response
   */
  200: JoinResponse;
};

export type JoinProjectResponse = JoinProjectResponses[keyof JoinProjectResponses];

export type BulkJoinProjectData = {
  /**
   * Req
   */
  body: Array<BulkJoinMember>;
  path: {
    /**
     * Project Id
     */
    project_id: string;
  };
  query?: never;
  url: "/projects/{project_id}/bulk-join";
};

export type BulkJoinProjectErrors = {
  /**
   * Conflict
   */
  409: ConflictResponse;
};

export type BulkJoinProjectError = BulkJoinProjectErrors[keyof BulkJoinProjectErrors];

export type BulkJoinProjectResponses = {
  /**
   * Successful Response
   */
  200: JoinResponse;
};

export type BulkJoinProjectResponse = BulkJoinProjectResponses[keyof BulkJoinProjectResponses];

export type SetProjectJoinPolicyData = {
  body: ModifyJoinPolicy;
  path: {
    /**
     * Project Id
     */
    project_id: string;
  };
  query?: never;
  url: "/projects/{project_id}/join-policy";
};

export type SetProjectJoinPolicyErrors = {
  /**
   * Forbidden
   */
  403: ForbiddenResponse;
  /**
   * Not Found
   */
  404: NotFoundResponse;
};

export type SetProjectJoinPolicyError =
  SetProjectJoinPolicyErrors[keyof SetProjectJoinPolicyErrors];

export type SetProjectJoinPolicyResponses = {
  /**
   * Successful Response
   */
  200: Projects;
};

export type SetProjectJoinPolicyResponse =
  SetProjectJoinPolicyResponses[keyof SetProjectJoinPolicyResponses];

export type LeaveProjectData = {
  body?: never;
  path: {
    /**
     * Project Id
     */
    project_id: string;
  };
  query?: never;
  url: "/projects/{project_id}/leave";
};

export type LeaveProjectErrors = {
  /**
   * Not Found
   */
  404: NotFoundResponse;
};

export type LeaveProjectError = LeaveProjectErrors[keyof LeaveProjectErrors];

export type LeaveProjectResponses = {
  /**
   * Successful Response
   */
  200: DeleteResponse;
};

export type LeaveProjectResponse = LeaveProjectResponses[keyof LeaveProjectResponses];

export type ListProjectInvitesData = {
  body?: never;
  path: {
    /**
     * Project Id
     */
    project_id: string;
  };
  query?: {
    /**
     * Status
     */
    status?: "pending" | "accepted" | "declined" | "revoked" | "expired" | null;
    /**
     * Kind
     */
    kind?: "invite" | "request" | null;
  };
  url: "/projects/{project_id}/invites";
};

export type ListProjectInvitesErrors = {
  /**
   * Forbidden
   */
  403: ForbiddenResponse;
};

export type ListProjectInvitesError = ListProjectInvitesErrors[keyof ListProjectInvitesErrors];

export type ListProjectInvitesResponses = {
  /**
   * Response 200 Listprojectinvites
   *
   * Successful Response
   */
  200: Array<ProjectInvite>;
};

export type ListProjectInvitesResponse =
  ListProjectInvitesResponses[keyof ListProjectInvitesResponses];

export type CreateInviteData = {
  body: CreateInvite;
  path: {
    /**
     * Project Id
     */
    project_id: string;
  };
  query?: never;
  url: "/projects/{project_id}/invites";
};

export type CreateInviteErrors = {
  /**
   * Forbidden
   */
  403: ForbiddenResponse;
  /**
   * Not Found
   */
  404: NotFoundResponse;
  /**
   * Conflict
   */
  409: ConflictResponse;
};

export type CreateInviteError = CreateInviteErrors[keyof CreateInviteErrors];

export type CreateInviteResponses = {
  /**
   * Successful Response
   */
  200: ProjectInvite;
};

export type CreateInviteResponse = CreateInviteResponses[keyof CreateInviteResponses];

export type CreateRequestData = {
  body: CreateRequest;
  path: {
    /**
     * Project Id
     */
    project_id: string;
  };
  query?: never;
  url: "/projects/{project_id}/requests";
};

export type CreateRequestErrors = {
  /**
   * Not Found
   */
  404: NotFoundResponse;
  /**
   * Conflict
   */
  409: ConflictResponse;
};

export type CreateRequestError = CreateRequestErrors[keyof CreateRequestErrors];

export type CreateRequestResponses = {
  /**
   * Successful Response
   */
  200: ProjectInvite;
};

export type CreateRequestResponse = CreateRequestResponses[keyof CreateRequestResponses];

export type AcceptProjectInviteData = {
  body?: never;
  path: {
    /**
     * Project Id
     */
    project_id: string;
    /**
     * Invite Id
     */
    invite_id: string;
  };
  query?: never;
  url: "/projects/{project_id}/invites/{invite_id}/accept";
};

export type AcceptProjectInviteErrors = {
  /**
   * Forbidden
   */
  403: ForbiddenResponse;
  /**
   * Not Found
   */
  404: NotFoundResponse;
  /**
   * Conflict
   */
  409: ConflictResponse;
  /**
   * Bad Gateway
   */
  502: HttpExceptionResponse;
};

export type AcceptProjectInviteError = AcceptProjectInviteErrors[keyof AcceptProjectInviteErrors];

export type AcceptProjectInviteResponses = {
  /**
   * Successful Response
   */
  200: InviteActionResponse;
};

export type AcceptProjectInviteResponse =
  AcceptProjectInviteResponses[keyof AcceptProjectInviteResponses];

export type DeclineProjectInviteData = {
  body?: never;
  path: {
    /**
     * Project Id
     */
    project_id: string;
    /**
     * Invite Id
     */
    invite_id: string;
  };
  query?: never;
  url: "/projects/{project_id}/invites/{invite_id}/decline";
};

export type DeclineProjectInviteErrors = {
  /**
   * Forbidden
   */
  403: ForbiddenResponse;
  /**
   * Not Found
   */
  404: NotFoundResponse;
  /**
   * Conflict
   */
  409: ConflictResponse;
  /**
   * Bad Gateway
   */
  502: HttpExceptionResponse;
};

export type DeclineProjectInviteError =
  DeclineProjectInviteErrors[keyof DeclineProjectInviteErrors];

export type DeclineProjectInviteResponses = {
  /**
   * Successful Response
   */
  200: InviteActionResponse;
};

export type DeclineProjectInviteResponse =
  DeclineProjectInviteResponses[keyof DeclineProjectInviteResponses];

export type RevokeProjectInviteData = {
  body?: never;
  path: {
    /**
     * Project Id
     */
    project_id: string;
    /**
     * Invite Id
     */
    invite_id: string;
  };
  query?: never;
  url: "/projects/{project_id}/invites/{invite_id}/revoke";
};

export type RevokeProjectInviteErrors = {
  /**
   * Forbidden
   */
  403: ForbiddenResponse;
  /**
   * Not Found
   */
  404: NotFoundResponse;
  /**
   * Conflict
   */
  409: ConflictResponse;
};

export type RevokeProjectInviteError = RevokeProjectInviteErrors[keyof RevokeProjectInviteErrors];

export type RevokeProjectInviteResponses = {
  /**
   * Successful Response
   */
  200: InviteActionResponse;
};

export type RevokeProjectInviteResponse =
  RevokeProjectInviteResponses[keyof RevokeProjectInviteResponses];

export type UploadMediaData = {
  body: UploadRequest;
  path: {
    /**
     * Project Id
     */
    project_id: string;
  };
  query?: never;
  url: "/projects/{project_id}/media/upload";
};

export type UploadMediaErrors = {
  /**
   * Bad Request
   */
  400: BadRequestResponse;
  /**
   * Forbidden
   */
  403: ForbiddenResponse;
  /**
   * Content Too Large
   */
  413: HttpExceptionResponse;
  /**
   * Unsupported Media Type
   */
  415: HttpExceptionResponse;
};

export type UploadMediaError = UploadMediaErrors[keyof UploadMediaErrors];

export type UploadMediaResponses = {
  /**
   * Response Uploadmedia
   *
   * Successful Response
   */
  200: MediaRecord | SimpleUploadResponse | MultipartUploadResponse;
};

export type UploadMediaResponse = UploadMediaResponses[keyof UploadMediaResponses];

export type CommitMediaData = {
  body: CommitRequest;
  path: {
    /**
     * Project Id
     */
    project_id: string;
  };
  query?: never;
  url: "/projects/{project_id}/media/commit";
};

export type CommitMediaErrors = {
  /**
   * Bad Request
   */
  400: BadRequestResponse;
  /**
   * Forbidden
   */
  403: ForbiddenResponse;
  /**
   * Not Found
   */
  404: NotFoundResponse;
  /**
   * Conflict
   */
  409: ConflictResponse;
  /**
   * Content Too Large
   */
  413: HttpExceptionResponse;
  /**
   * Unsupported Media Type
   */
  415: HttpExceptionResponse;
  /**
   * Bad Gateway
   */
  502: HttpExceptionResponse;
};

export type CommitMediaError = CommitMediaErrors[keyof CommitMediaErrors];

export type CommitMediaResponses = {
  /**
   * Successful Response
   */
  200: MediaRecord;
};

export type CommitMediaResponse = CommitMediaResponses[keyof CommitMediaResponses];

export type UploadProjectThumbnailData = {
  body: UploadRequest;
  path: {
    /**
     * Project Id
     */
    project_id: string;
  };
  query?: never;
  url: "/projects/{project_id}/thumbnail/upload";
};

export type UploadProjectThumbnailErrors = {
  /**
   * Bad Request
   */
  400: BadRequestResponse;
  /**
   * Forbidden
   */
  403: ForbiddenResponse;
  /**
   * Content Too Large
   */
  413: HttpExceptionResponse;
};

export type UploadProjectThumbnailError =
  UploadProjectThumbnailErrors[keyof UploadProjectThumbnailErrors];

export type UploadProjectThumbnailResponses = {
  /**
   * Response Uploadprojectthumbnail
   *
   * Successful Response
   */
  200: MediaRecord;
};

export type UploadProjectThumbnailResponse =
  UploadProjectThumbnailResponses[keyof UploadProjectThumbnailResponses];

export type CommitProjectThumbnailData = {
  body: UploadRequest;
  path: {
    /**
     * Project Id
     */
    project_id: string;
  };
  query?: never;
  url: "/projects/{project_id}/thumbnail/commit";
};

export type CommitProjectThumbnailErrors = {
  /**
   * Bad Request
   */
  400: BadRequestResponse;
  /**
   * Forbidden
   */
  403: ForbiddenResponse;
  /**
   * Not Found
   */
  404: NotFoundResponse;
  /**
   * Conflict
   */
  409: ConflictResponse;
  /**
   * Content Too Large
   */
  413: HttpExceptionResponse;
};

export type CommitProjectThumbnailError =
  CommitProjectThumbnailErrors[keyof CommitProjectThumbnailErrors];

export type CommitProjectThumbnailResponses = {
  /**
   * Successful Response
   */
  200: ProjectThumbnail;
};

export type CommitProjectThumbnailResponse =
  CommitProjectThumbnailResponses[keyof CommitProjectThumbnailResponses];

export type RemoveProjectThumbnailData = {
  body?: never;
  path: {
    /**
     * Project Id
     */
    project_id: string;
  };
  query?: never;
  url: "/projects/{project_id}/thumbnail";
};

export type RemoveProjectThumbnailErrors = {
  /**
   * Forbidden
   */
  403: ForbiddenResponse;
  /**
   * Not Found
   */
  404: NotFoundResponse;
};

export type RemoveProjectThumbnailError =
  RemoveProjectThumbnailErrors[keyof RemoveProjectThumbnailErrors];

export type RemoveProjectThumbnailResponses = {
  /**
   * Successful Response
   */
  200: DeleteResponse;
};

export type RemoveProjectThumbnailResponse =
  RemoveProjectThumbnailResponses[keyof RemoveProjectThumbnailResponses];

export type SetProjectThumbnailData = {
  body: SetThumbnailRequest;
  path: {
    /**
     * Project Id
     */
    project_id: string;
  };
  query?: never;
  url: "/projects/{project_id}/thumbnail";
};

export type SetProjectThumbnailErrors = {
  /**
   * Bad Request
   */
  400: BadRequestResponse;
  /**
   * Forbidden
   */
  403: ForbiddenResponse;
  /**
   * Not Found
   */
  404: NotFoundResponse;
};

export type SetProjectThumbnailError = SetProjectThumbnailErrors[keyof SetProjectThumbnailErrors];

export type SetProjectThumbnailResponses = {
  /**
   * Successful Response
   */
  200: SuccessResponse;
};

export type SetProjectThumbnailResponse =
  SetProjectThumbnailResponses[keyof SetProjectThumbnailResponses];

export type ListProjectMediaData = {
  body?: never;
  path: {
    /**
     * Project Id
     */
    project_id: string;
  };
  query?: never;
  url: "/projects/{project_id}/media";
};

export type ListProjectMediaErrors = {
  /**
   * Forbidden
   */
  403: ForbiddenResponse;
};

export type ListProjectMediaError = ListProjectMediaErrors[keyof ListProjectMediaErrors];

export type ListProjectMediaResponses = {
  /**
   * Response 200 Listprojectmedia
   *
   * Successful Response
   */
  200: Array<MediaRecord>;
};

export type ListProjectMediaResponse = ListProjectMediaResponses[keyof ListProjectMediaResponses];

export type ReorderProjectMediaData = {
  body: ReorderRequest;
  path: {
    /**
     * Project Id
     */
    project_id: string;
  };
  query?: never;
  url: "/projects/{project_id}/media/positions";
};

export type ReorderProjectMediaErrors = {
  /**
   * Forbidden
   */
  403: ForbiddenResponse;
  /**
   * Not Found
   */
  404: NotFoundResponse;
};

export type ReorderProjectMediaError = ReorderProjectMediaErrors[keyof ReorderProjectMediaErrors];

export type ReorderProjectMediaResponses = {
  /**
   * Successful Response
   */
  200: SuccessResponse;
};

export type ReorderProjectMediaResponse =
  ReorderProjectMediaResponses[keyof ReorderProjectMediaResponses];

export type RemoveProjectMediaData = {
  body?: never;
  path: {
    /**
     * Project Id
     */
    project_id: string;
    /**
     * Media Hash
     */
    media_hash: string;
  };
  query?: never;
  url: "/projects/{project_id}/media/{media_hash}";
};

export type RemoveProjectMediaErrors = {
  /**
   * Forbidden
   */
  403: ForbiddenResponse;
  /**
   * Not Found
   */
  404: NotFoundResponse;
};

export type RemoveProjectMediaError = RemoveProjectMediaErrors[keyof RemoveProjectMediaErrors];

export type RemoveProjectMediaResponses = {
  /**
   * Successful Response
   */
  200: DeleteResponse;
};

export type RemoveProjectMediaResponse =
  RemoveProjectMediaResponses[keyof RemoveProjectMediaResponses];

export type GetTagsData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Title
     */
    title?: string | null;
  };
  url: "/tags";
};

export type GetTagsResponses = {
  /**
   * Response Gettags
   *
   * Successful Response
   */
  200: Array<FullTags>;
};

export type GetTagsResponse = GetTagsResponses[keyof GetTagsResponses];

export type DeleteTagData = {
  body?: never;
  path: {
    /**
     * Tag Id
     */
    tag_id: number;
  };
  query?: never;
  url: "/tags/{tag_id}";
};

export type DeleteTagErrors = {
  /**
   * Not Found
   */
  404: NotFoundResponse;
  /**
   * Conflict
   */
  409: AttachedTagResponse;
};

export type DeleteTagError = DeleteTagErrors[keyof DeleteTagErrors];

export type DeleteTagResponses = {
  /**
   * Successful Response
   */
  200: DeleteResponse;
};

export type DeleteTagResponse = DeleteTagResponses[keyof DeleteTagResponses];

export type GetTagByIdData = {
  body?: never;
  path: {
    /**
     * Tag Id
     */
    tag_id: number;
  };
  query?: never;
  url: "/tags/{tag_id}";
};

export type GetTagByIdErrors = {
  /**
   * Not Found
   */
  404: NotFoundResponse;
};

export type GetTagByIdError = GetTagByIdErrors[keyof GetTagByIdErrors];

export type GetTagByIdResponses = {
  /**
   * Successful Response
   */
  200: FullTags;
};

export type GetTagByIdResponse = GetTagByIdResponses[keyof GetTagByIdResponses];

export type EditTagData = {
  body: ModifiedTag;
  path: {
    /**
     * Tag Id
     */
    tag_id: number;
  };
  query?: never;
  url: "/tags/{tag_id}";
};

export type EditTagErrors = {
  /**
   * Not Found
   */
  404: NotFoundResponse;
};

export type EditTagError = EditTagErrors[keyof EditTagErrors];

export type EditTagResponses = {
  /**
   * Successful Response
   */
  200: Tags;
};

export type EditTagResponse = EditTagResponses[keyof EditTagResponses];

export type CreateTagsData = {
  body: ModifiedTag;
  path?: never;
  query?: never;
  url: "/tags/create";
};

export type CreateTagsResponses = {
  /**
   * Successful Response
   */
  200: Tags;
};

export type CreateTagsResponse = CreateTagsResponses[keyof CreateTagsResponses];

export type BulkCreateTagsData = {
  /**
   * Req
   */
  body: Array<ModifiedTag>;
  path?: never;
  query?: never;
  url: "/tags/bulk-create";
};

export type BulkCreateTagsResponses = {
  /**
   * Response 200 Bulkcreatetags
   *
   * Successful Response
   */
  200: Array<Tags>;
};

export type BulkCreateTagsResponse = BulkCreateTagsResponses[keyof BulkCreateTagsResponses];
