/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as ErrorRouteImport } from './routes/error'
import { Route as EventsRouteImport } from './routes/events'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as SigsRouteImport } from './routes/sigs'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardEventsRouteImport } from './routes/dashboard/events'
import { Route as DashboardProjectsRouteImport } from './routes/dashboard/projects'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard/settings'
import { Route as ProjectProjectIdRouteImport } from './routes/project/$projectId'
import { Route as DashboardAdminMembersRouteImport } from './routes/dashboard/admin/members'
import { Route as DashboardAdminOverviewRouteImport } from './routes/dashboard/admin/overview'
import { Route as DashboardAdminTagsRouteImport } from './routes/dashboard/admin/tags'
import { Route as DashboardEventsPastRouteImport } from './routes/dashboard/events_.past'
import { Route as DashboardManageEventsRouteImport } from './routes/dashboard/manage/events'
import { Route as DashboardManageProjectsRouteImport } from './routes/dashboard/manage/projects'
import { Route as DashboardManageProjectsProjectIdGalleryRouteImport } from './routes/dashboard/manage/projects_.$projectId.gallery'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ErrorRoute = ErrorRouteImport.update({
  id: '/error',
  path: '/error',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const SigsRoute = SigsRouteImport.update({
  id: '/sigs',
  path: '/sigs',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardEventsRoute = DashboardEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardProjectsRoute = DashboardProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const ProjectProjectIdRoute = ProjectProjectIdRouteImport.update({
  id: '/project/$projectId',
  path: '/project/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAdminMembersRoute = DashboardAdminMembersRouteImport.update({
  id: '/admin/members',
  path: '/admin/members',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardAdminOverviewRoute = DashboardAdminOverviewRouteImport.update({
  id: '/admin/overview',
  path: '/admin/overview',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardAdminTagsRoute = DashboardAdminTagsRouteImport.update({
  id: '/admin/tags',
  path: '/admin/tags',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardEventsPastRoute = DashboardEventsPastRouteImport.update({
  id: '/events_/past',
  path: '/events/past',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardManageEventsRoute = DashboardManageEventsRouteImport.update({
  id: '/manage/events',
  path: '/manage/events',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardManageProjectsRoute = DashboardManageProjectsRouteImport.update({
  id: '/manage/projects',
  path: '/manage/projects',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardManageProjectsProjectIdGalleryRoute =
  DashboardManageProjectsProjectIdGalleryRouteImport.update({
    id: '/manage/projects_/$projectId/gallery',
    path: '/manage/projects/$projectId/gallery',
    getParentRoute: () => DashboardRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/error': typeof ErrorRoute
  '/events': typeof EventsRoute
  '/login': typeof LoginRoute
  '/projects': typeof ProjectsRoute
  '/register': typeof RegisterRoute
  '/sigs': typeof SigsRoute
  '/dashboard/events': typeof DashboardEventsRoute
  '/dashboard/projects': typeof DashboardProjectsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/project/$projectId': typeof ProjectProjectIdRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/admin/members': typeof DashboardAdminMembersRoute
  '/dashboard/admin/overview': typeof DashboardAdminOverviewRoute
  '/dashboard/admin/tags': typeof DashboardAdminTagsRoute
  '/dashboard/events/past': typeof DashboardEventsPastRoute
  '/dashboard/manage/events': typeof DashboardManageEventsRoute
  '/dashboard/manage/projects': typeof DashboardManageProjectsRoute
  '/dashboard/manage/projects/$projectId/gallery': typeof DashboardManageProjectsProjectIdGalleryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/error': typeof ErrorRoute
  '/events': typeof EventsRoute
  '/login': typeof LoginRoute
  '/projects': typeof ProjectsRoute
  '/register': typeof RegisterRoute
  '/sigs': typeof SigsRoute
  '/dashboard/events': typeof DashboardEventsRoute
  '/dashboard/projects': typeof DashboardProjectsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/project/$projectId': typeof ProjectProjectIdRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/admin/members': typeof DashboardAdminMembersRoute
  '/dashboard/admin/overview': typeof DashboardAdminOverviewRoute
  '/dashboard/admin/tags': typeof DashboardAdminTagsRoute
  '/dashboard/events/past': typeof DashboardEventsPastRoute
  '/dashboard/manage/events': typeof DashboardManageEventsRoute
  '/dashboard/manage/projects': typeof DashboardManageProjectsRoute
  '/dashboard/manage/projects/$projectId/gallery': typeof DashboardManageProjectsProjectIdGalleryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/error': typeof ErrorRoute
  '/events': typeof EventsRoute
  '/login': typeof LoginRoute
  '/projects': typeof ProjectsRoute
  '/register': typeof RegisterRoute
  '/sigs': typeof SigsRoute
  '/dashboard/events': typeof DashboardEventsRoute
  '/dashboard/projects': typeof DashboardProjectsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/project/$projectId': typeof ProjectProjectIdRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/admin/members': typeof DashboardAdminMembersRoute
  '/dashboard/admin/overview': typeof DashboardAdminOverviewRoute
  '/dashboard/admin/tags': typeof DashboardAdminTagsRoute
  '/dashboard/events_/past': typeof DashboardEventsPastRoute
  '/dashboard/manage/events': typeof DashboardManageEventsRoute
  '/dashboard/manage/projects': typeof DashboardManageProjectsRoute
  '/dashboard/manage/projects_/$projectId/gallery': typeof DashboardManageProjectsProjectIdGalleryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/about'
    | '/error'
    | '/events'
    | '/login'
    | '/projects'
    | '/register'
    | '/sigs'
    | '/dashboard/events'
    | '/dashboard/projects'
    | '/dashboard/settings'
    | '/project/$projectId'
    | '/dashboard/'
    | '/dashboard/admin/members'
    | '/dashboard/admin/overview'
    | '/dashboard/admin/tags'
    | '/dashboard/events/past'
    | '/dashboard/manage/events'
    | '/dashboard/manage/projects'
    | '/dashboard/manage/projects/$projectId/gallery'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/error'
    | '/events'
    | '/login'
    | '/projects'
    | '/register'
    | '/sigs'
    | '/dashboard/events'
    | '/dashboard/projects'
    | '/dashboard/settings'
    | '/project/$projectId'
    | '/dashboard'
    | '/dashboard/admin/members'
    | '/dashboard/admin/overview'
    | '/dashboard/admin/tags'
    | '/dashboard/events/past'
    | '/dashboard/manage/events'
    | '/dashboard/manage/projects'
    | '/dashboard/manage/projects/$projectId/gallery'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/about'
    | '/error'
    | '/events'
    | '/login'
    | '/projects'
    | '/register'
    | '/sigs'
    | '/dashboard/events'
    | '/dashboard/projects'
    | '/dashboard/settings'
    | '/project/$projectId'
    | '/dashboard/'
    | '/dashboard/admin/members'
    | '/dashboard/admin/overview'
    | '/dashboard/admin/tags'
    | '/dashboard/events_/past'
    | '/dashboard/manage/events'
    | '/dashboard/manage/projects'
    | '/dashboard/manage/projects_/$projectId/gallery'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  ErrorRoute: typeof ErrorRoute
  EventsRoute: typeof EventsRoute
  LoginRoute: typeof LoginRoute
  ProjectsRoute: typeof ProjectsRoute
  RegisterRoute: typeof RegisterRoute
  SigsRoute: typeof SigsRoute
  ProjectProjectIdRoute: typeof ProjectProjectIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/error': {
      id: '/error'
      path: '/error'
      fullPath: '/error'
      preLoaderRoute: typeof ErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sigs': {
      id: '/sigs'
      path: '/sigs'
      fullPath: '/sigs'
      preLoaderRoute: typeof SigsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/events': {
      id: '/dashboard/events'
      path: '/events'
      fullPath: '/dashboard/events'
      preLoaderRoute: typeof DashboardEventsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/projects': {
      id: '/dashboard/projects'
      path: '/projects'
      fullPath: '/dashboard/projects'
      preLoaderRoute: typeof DashboardProjectsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/project/$projectId': {
      id: '/project/$projectId'
      path: '/project/$projectId'
      fullPath: '/project/$projectId'
      preLoaderRoute: typeof ProjectProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/admin/members': {
      id: '/dashboard/admin/members'
      path: '/admin/members'
      fullPath: '/dashboard/admin/members'
      preLoaderRoute: typeof DashboardAdminMembersRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/admin/overview': {
      id: '/dashboard/admin/overview'
      path: '/admin/overview'
      fullPath: '/dashboard/admin/overview'
      preLoaderRoute: typeof DashboardAdminOverviewRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/admin/tags': {
      id: '/dashboard/admin/tags'
      path: '/admin/tags'
      fullPath: '/dashboard/admin/tags'
      preLoaderRoute: typeof DashboardAdminTagsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/events_/past': {
      id: '/dashboard/events_/past'
      path: '/events/past'
      fullPath: '/dashboard/events/past'
      preLoaderRoute: typeof DashboardEventsPastRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/manage/events': {
      id: '/dashboard/manage/events'
      path: '/manage/events'
      fullPath: '/dashboard/manage/events'
      preLoaderRoute: typeof DashboardManageEventsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/manage/projects': {
      id: '/dashboard/manage/projects'
      path: '/manage/projects'
      fullPath: '/dashboard/manage/projects'
      preLoaderRoute: typeof DashboardManageProjectsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/manage/projects_/$projectId/gallery': {
      id: '/dashboard/manage/projects_/$projectId/gallery'
      path: '/manage/projects/$projectId/gallery'
      fullPath: '/dashboard/manage/projects/$projectId/gallery'
      preLoaderRoute: typeof DashboardManageProjectsProjectIdGalleryRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
  }
}

interface DashboardRouteRouteChildren {
  DashboardEventsRoute: typeof DashboardEventsRoute
  DashboardProjectsRoute: typeof DashboardProjectsRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardAdminMembersRoute: typeof DashboardAdminMembersRoute
  DashboardAdminOverviewRoute: typeof DashboardAdminOverviewRoute
  DashboardAdminTagsRoute: typeof DashboardAdminTagsRoute
  DashboardEventsPastRoute: typeof DashboardEventsPastRoute
  DashboardManageEventsRoute: typeof DashboardManageEventsRoute
  DashboardManageProjectsRoute: typeof DashboardManageProjectsRoute
  DashboardManageProjectsProjectIdGalleryRoute: typeof DashboardManageProjectsProjectIdGalleryRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardEventsRoute: DashboardEventsRoute,
  DashboardProjectsRoute: DashboardProjectsRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardAdminMembersRoute: DashboardAdminMembersRoute,
  DashboardAdminOverviewRoute: DashboardAdminOverviewRoute,
  DashboardAdminTagsRoute: DashboardAdminTagsRoute,
  DashboardEventsPastRoute: DashboardEventsPastRoute,
  DashboardManageEventsRoute: DashboardManageEventsRoute,
  DashboardManageProjectsRoute: DashboardManageProjectsRoute,
  DashboardManageProjectsProjectIdGalleryRoute:
    DashboardManageProjectsProjectIdGalleryRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  ErrorRoute: ErrorRoute,
  EventsRoute: EventsRoute,
  LoginRoute: LoginRoute,
  ProjectsRoute: ProjectsRoute,
  RegisterRoute: RegisterRoute,
  SigsRoute: SigsRoute,
  ProjectProjectIdRoute: ProjectProjectIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
