name: Docker

on:
  push:
    branches: [react-rewrite]
    tags: ["v*"]

jobs:
  Build-and-Push:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7

      - name: Prepare Docker Meta
        id: meta
        uses: docker/metadata-action@dc802804100637a589fabce1cb79ff13a1411302 # v6
        with:
          images: |
            ghcr.io/ucmercedacm/chapter-website
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=edge,branch=react-rewrite

      - name: Setup Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@bb05f3f5519dd87d3ba754cc423b652a5edd6d2c # v4
        with:
          version: latest

      - name: Login to GitHub Container Registry
        uses: docker/login-action@c99871dec2022cc055c062a10cc1a1310835ceb4 # v4
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a # v7
        with:
          context: .
          file: ./docker/Dockerfile
          push: true
          cache-from: type=registry,ref=ghcr.io/ucmercedacm/chapter-website-build-cache:app
          cache-to: type=registry,mode=max,ref=ghcr.io/ucmercedacm/chapter-website-build-cache:app
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
