name: Lint
on:
  push:
    branches:
      - react-rewrite

  pull_request:
    branches:
      - react-rewrite

jobs:
  Check:
    runs-on: ubuntu-24.04

    env:
      ESLINT_CACHE_DIR: /tmp/.eslintcache

    steps:
      - name: Checkout Repository  
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: Set up Node
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7
        with:
          node-version: lts/*

      - name: Install pnpm
        uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6
        with:
          version: latest

      - name: Restore ESLint cache
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6
        with:
          path: ${{ env.ESLINT_CACHE_DIR }}
          key: eslint-${{ runner.os }}-${{ hashFiles('eslint.config.js') }}
          restore-keys: |
            eslint-${{ runner.os }}-${{ hashFiles('eslint.config.js') }}
            eslint-${{ runner.os }}

      - name: Install dependencies
        run: |
          pnpm install --frozen-lockfile --ignore-scripts
      
      - name: Check codebase via Oxlint
        run: |
          pnpm exec oxlint --type-check --type-aware --deny-warnings src

      - name: Check codebase via ESLint
        run: |
          pnpm exec eslint src --cache --cache-location $ESLINT_CACHE_DIR

      - name: Check for formatting
        run: |
          pnpm exec oxfmt --check src

